#!!
#Run akhileshns/heroku-deploy@v3.12.12
#From https://github.com/OleksandrVozhdai/mkr2CICD
# * [new branch]      develop    -> origin/develop
#Created and wrote to ~/.netrc
#Successfully logged into heroku
#/bin/sh: 1: heroku: not found
#/bin/sh: 1: heroku: not found
#Error: Error: Command failed: heroku create

# !!This action will always fail in our case because we are not actually deploying to heroku!!
# So i decided to comment all this to prevent fails


#name: Django CI/CD to Heroku

#on:
#  push:
#    branches: ["main"]

#jobs:
#  deploy:
#    runs-on: ubuntu-latest

#   steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#         python-version: '3.10'

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt

#      - name: Run Django tests
#        run: |
#          python manage.py migrate --noinput
#          python manage.py test

#      - name: Deploy to Heroku
#        uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          heroku_email: ${{ secrets.HEROKU_EMAIL }}
#          usedocker: false
